name: Deploy Pull Request to main Environment

on:
  push:
    branches: [main]

jobs:
  build_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: edit .env file
        env:
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          ENABLE_LOGS: ${{ secrets.ENABLE_LOGS }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
          KAFKA_TOPIC_LOGIN: ${{ secrets.KAFKA_TOPIC_LOGIN }}
          KAFKA_TOPIC_lOGOUT: ${{ secrets.KAFKA_TOPIC_lOGOUT }}
          KAFKA_TOPIC_PASS_RESET: ${{ secrets.KAFKA_TOPIC_PASS_RESET }}
          KAFKA_TOPIC_CREATE_USER: ${{ secrets.KAFKA_TOPIC_CREATE_USER }}
          KAFKA_TOPIC_DELETE_USER: ${{ secrets.KAFKA_TOPIC_DELETE_USER }}
          KAFKA_TOPIC_EDIT_USER: ${{ secrets.KAFKA_TOPIC_EDIT_USER }}
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
        run: |
          echo "PORT=${PORT}" > .env
          echo "MONGO_URI=${MONGO_URI}" >> .env
          echo "REDIS_HOST=${REDIS_HOST}" >> .env
          echo "REDIS_PORT=${REDIS_PORT}" >> .env
          echo "ENABLE_LOGS=${ENABLE_LOGS}" >> .env
          echo "ENCRYPTION_KEY=${ENCRYPTION_KEY}" >> .env
          echo "ENCRYPTION_IV=${ENCRYPTION_IV}" >> .env
          echo "KAFKA_TOPIC_LOGIN=${KAFKA_TOPIC_LOGIN}" >> .env
          echo "KAFKA_TOPIC_lOGOUT=${KAFKA_TOPIC_lOGOUT}" >> .env
          echo "KAFKA_TOPIC_PASS_RESET=${KAFKA_TOPIC_PASS_RESET}" >> .env
          echo "KAFKA_TOPIC_CREATE_USER=${KAFKA_TOPIC_CREATE_USER}" >> .env
          echo "KAFKA_TOPIC_DELETE_USER=${KAFKA_TOPIC_DELETE_USER}" >> .env
          echo "KAFKA_TOPIC_EDIT_USER=${KAFKA_TOPIC_EDIT_USER}" >> .env
          echo "KAFKA_BROKER=${KAFKA_BROKER}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: byvoxel/mark4users
          tags: |
            type=raw,value=staging
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: byvoxel/mark4users:staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_to_ec2:
    name: Deploy to EC2 Instances
    runs-on: ubuntu-latest
    needs: build_docker_image
    strategy:
      matrix:
        ec2_instance: 
          - ec2-54-172-13-82.compute-1.amazonaws.com

    steps:
      - name: Deploy Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ matrix.ec2_instance }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: "120s"
          script: |
            set -e
            echo "Deploying image: byvoxel/mark4users:staging"
            sudo docker stop mark4users || true
            sudo docker rm mark4users || true
            sudo docker pull byvoxel/mark4users:staging
            sudo docker run -d \
              --name mark4users \
              -p 3090:3090 \
              --restart unless-stopped \
              byvoxel/mark4users:staging
            sudo docker system prune -af --volumes || true